"""Initial migration

Revision ID: 001f0b24118b
Revises: 
Create Date: 2025-08-27 06:18:18.962580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001f0b24118b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_url', sa.String(length=500), nullable=False),
    sa.Column('claim_data', sa.JSON(), nullable=False),
    sa.Column('origin_document_id', sa.String(length=36), nullable=True),
    sa.Column('validation_claims', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['origin_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_url')
    )
    op.create_table('draft_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('object', sa.String(length=500), nullable=True),
    sa.Column('claim_data', sa.JSON(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('page_text_snippet', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('linkedtrust_claim_url', sa.String(length=500), nullable=True),
    sa.Column('linkedtrust_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_jobs')
    op.drop_table('draft_claims')
    op.drop_table('claim_cache')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
