"""Add subject_url field to Document model

Revision ID: 3f83a761e1c7
Revises: 001f0b24118b
Create Date: 2025-09-15 09:17:14.124354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f83a761e1c7'
down_revision = '001f0b24118b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('subject_url')

    # ### end Alembic commands ###
